# Generated by Django 3.2.12 on 2024-02-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jokes",
            name="offense_type",
            field=models.CharField(
                choices=[
                    ("RACE", "Race"),
                    ("RELIGION", "Religion"),
                    ("ETHNICITY", "Ethnicity"),
                    ("GENDER", "Gender"),
                    ("SEXUAL_ORIENTATION", "Sexual Orientation"),
                    ("DISABILITY", "Disability"),
                ],
                default="RACE",
                max_length=50,
            ),
        ),
    ]
