# Generated by Django 3.2.12 on 2024-02-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jokes_offense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='offense_degree',
            field=models.IntegerField(default=0),
        ),
    ]
