# Generated by Django 3.2.12 on 2024-02-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_joke_offense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='offense_type',
            field=models.CharField(choices=[('RACE', 'Race'), ('RELIGION', 'Religion'), ('ETHNICITY', 'Ethnicity'), ('GENDER', 'Gender'), ('SEXUAL_ORIENTATION', 'Sexual Orientation'), ('DISABILITY', 'Disability'), ('NO_OFFENSE_FOUND', 'No Offense Found')], max_length=50, null=True),
        ),
    ]
