# Generated by Django 3.2.12 on 2024-02-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_joke_offense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='language',
            field=models.CharField(default='Spanish', max_length=100),
        ),
    ]
