# Generated by Django 3.2.12 on 2024-03-01 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20240301_1532"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jokometian",
            name="image",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="url",
        ),
        migrations.AddField(
            model_name="jokometian",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
