# Generated by Django 3.2.12 on 2024-03-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20240301_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JokesEvaluation',
            new_name='JokeEvaluation',
        ),
    ]
