# Generated by Django 3.2.12 on 2024-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_jokesevaluation_jokeevaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationsession",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
