# Generated by Django 3.2.12 on 2024-03-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20240302_1142"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffenseTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("RACE", "Race"),
                            ("RELIGION", "Religion"),
                            ("ETHNICITY", "Ethnicity"),
                            ("GENDER", "Gender"),
                            ("SEXUAL_ORIENTATION", "Sexual Orientation"),
                            ("DISABILITY", "Disability"),
                            ("GENERIC_VIOLENCE", "Generic Violence"),
                            ("NO_OFFENSE_FOUND", "No Offense Found"),
                        ],
                        max_length=50,
                    ),
                ),
                ("degree", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="disability_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="ethnicity_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="gender_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="no_offense_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="race_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="religion_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="sexual_orientation_rate",
        ),
        migrations.RemoveField(
            model_name="jokometian",
            name="violence_rate",
        ),
        migrations.AlterField(
            model_name="joke",
            name="offense_type",
            field=models.CharField(
                choices=[
                    ("RACE", "Race"),
                    ("RELIGION", "Religion"),
                    ("ETHNICITY", "Ethnicity"),
                    ("GENDER", "Gender"),
                    ("SEXUAL_ORIENTATION", "Sexual Orientation"),
                    ("DISABILITY", "Disability"),
                    ("GENERIC_VIOLENCE", "Generic Violence"),
                    ("NO_OFFENSE_FOUND", "No Offense Found"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joke",
            name="trait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.offensetrait",
            ),
        ),
        migrations.AddField(
            model_name="jokometian",
            name="traits",
            field=models.ManyToManyField(to="api.OffenseTrait"),
        ),
    ]
