# Generated by Django 3.2.12 on 2024-03-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20240306_0942"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offensetrait",
            unique_together={("name", "degree")},
        ),
    ]
