# Generated by Django 3.2.12 on 2024-03-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_offensetrait_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Jokometian",
        ),
    ]
